spring:
  application:
    name: notification-service
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:8082}
